gopush:
  node-server:
    name: NodeServer001
    node-port: 9002
    device-port: 9001


spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379


server:
  port: 8001

