go-push:
  node-server:
    name: NodeServer001
    node-port: 9002
    device-port: 9001
    batch-processor:
      delay: 1000
      batch-size: 300
      warn-threshold: 300
      processor-size: 2
      core-pool-size: 1

  zookeeper:
      servers: 192.168.99.100:32768,192.168.99.100:32769,192.168.99.100:32770
      listen-namespace: datacenter
      namespace: nodeserver
      session-timeout: 6000
      connection-timeout: 6000
      max-retries: 1000
      retries-sleep-time: 2000



spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379


server:
  port: 8001

