gopush:
  node-server:
    name: NodeServer001
    node-port: 9002
    device-port: 9001

redis:
  cluster:
    servers: 127.0.0.1:6379
    dockedServers: 127.0.0.1:6379
    poolSize: 40
    timeout: 5000
server:
  port: 8001

