go-push:
  data-center: dataCenter001
  zookeeper:
      servers: 192.168.99.100:32774,192.168.99.100:32775,192.168.99.100:32776
      namespace: data-center
      session-timeout: 6000
      connection-timeout: 6000
      max-retries: 1000
      retries-sleep-time: 2000

spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379



server:
  port: 8031
