go-push:
  data-center:
    name: dataCenter001
  zookeeper:
      servers: 192.168.99.100:32768,192.168.99.100:32769,192.168.99.100:32770
      listen-namespace: nodeserver
      namespace: datacenter
      session-timeout: 6000
      connection-timeout: 6000
      max-retries: 1000
      retries-sleep-time: 2000

spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379



server:
  port: 8031
